- src/components/cart/CartSummary.tsx
- src/components/order/Address.tsx
- src/screens/FoodDetail.tsx
- src/screens/orderScreen/AddressEdit.tsx
- src/screens/orderScreen/Order.tsx
- src/stores/slices/userInputSlice.ts
- src/styles/styledConsts.tsx
변수 isValidAll 로 CTA버튼을 활성/비활성 결정
isValidAll을 redux값인  addr1.value, addr2.value, zipcode.value 로 확인했던 것 오류
=> 주소값은 사용자 input기준이 아니라 address버튼 눌렀을 때 체크표시되는 값을 기준으로 해야함
==> listAddressData[selectedAddrIdx].addr1/2/zipCode 값으로 validation 필요
(23.11.21)
> [FIX] : [Order] 주문버튼 validation오류 수정

- src/components/foodDetail/FoodPart.tsx
- src/components/home/Filter.tsx
- src/query/queries/product.ts
- src/screens/FoodDetail.tsx
filter 적용 후 서버 request 보낼 때 params에 각 필터마다
"|" 로 구분해서 넣어주어야 함
(23.11.22 : fixed by 대갈딱딱)
> [FIX] : 필터 두 가지 이상 적용한 경우 오류나는 것 수정

- src/components/cart/AccordionInactiveHeader.tsx
- src/components/cart/CartFoodList.tsx
- src/components/cart/CartSummary.tsx
- src/components/cart/Menu.tsx
- src/components/home/FoodList.tsx
- src/constants/constants.ts
- src/query/queries/product.ts
- src/screens/Cart.tsx
- src/screens/FoodDetail.tsx
- src/screens/Home.tsx
- src/screens/myPageScreen/orderHistory/OrderHistory.tsx
- src/screens/myPageScreen/orderHistory/OrderHistoryDetail.tsx
- src/util/cart/autoMenu2.ts
- src/util/sumUp.ts
SERVICE_PRICE_PER_PRODUCT = 300 으로 적용,
[FoodDetail] 현재 장바구니에 담긴 판매자 상품가격 보이는 기능도 추가.
(23.11.24 작성 by 대갈딱딱이)
> [FEATURE] : 서비스 가격 식품 가격에 포함시키기

- src/util/cart/autoMenu2.ts
available foods가 없을 때, 초기 정보로 리셋해주는 부분이 빠져있었음.
(23.11.23 fixed by 대갈딱딱이)
> [FIX] : 자동구성 오류 수정 <autoMenu2.ts>

- src/components/common/businessInfo/BusinessInfo.tsx
- src/constants/constants.ts
- src/screens/FoodDetail.tsx
- src/screens/myPageScreen/Mypage.tsx
- src/screens/myPageScreen/orderHistory/OrderHistoryDetail.tsx
- src/screens/orderScreen/Order.tsx
1. 사업자정보 이메일, 대표번호 추가
2. 사업자정보 디자인 수정
3. 문의채널 (카톡1:1채팅) 더 잘 보이게 추가 => 마이페이지, 주문내역 상세페이지
(23.11.28 fixed by 대갈딱딱이)
> [FIX] : pg심사 준비 (부가사업자정보, 문의채널 추가)

- src/screens/orderScreen/OrderComplete.tsx
주문완료 후 배송 관련 문의 방법 공지
(23.11.28 fixed by 대갈딱딱이)
> [FIX] : [OrderComplete] 문구 수정

- android/app/build.gradle
1. 필터오류 수정
2. 서비스금액 추가
3. 카카오페이 onSuccess 오류 수정
4. 자동구성 오류 수정
5. 부가사업자정보, 문의채널 추가 (pg심사용)
6. orderComplete 문구 수정
> [RELEASE] version 1.0.2 (23.11.30)

- src/components/common/businessInfo/BusinessInfo.tsx
- src/components/foodDetail/ShippingPart.tsx
- src/components/home/FlatlistHeaderComponent.tsx
- src/components/home/FoodList.tsx
- src/screens/FoodDetail.tsx
- src/screens/Home.tsx
- src/screens/Likes.tsx
- src/screens/orderScreen/Order.tsx
1. 메인화면 [Main] 하단 사업자정보 추가 (메인화면, 좋아요 화면 flatlist관련 margin, padding 수정)
2. 식품상세페이지 [FoodDetail] 배송기간공지 추가
(23.12.04 added by 대갈딱딱이)
> [FEAT] : 메인화면 하단 사업자정보 추가, 배송기간공지 추가

- node_modules/iamport-react-native/src/components/Loading/index.tsx
- src/components/cart/CartSummary.tsx
- src/components/home/Filter.tsx
- src/components/home/FlatlistHeaderComponent.tsx
- src/screens/Cart.tsx
- src/screens/Home.tsx
- src/screens/orderScreen/Order.tsx
- src/stores/slices/orderSlice.ts
- src/util/sumUp.ts
1. 하단에 seller 돋보기 아이콘 정렬
2. 돋보기 아이콘 눌렀을때 홈화면으로 이동 및 검색창 open
3. 홈 화면에서 초기화 버튼 눌렀을 때 검색창 close
4. 빨간줄 수정
> [FEAT]: cartSummary 디자인 수정, 기능 수정

- android/app/build.gradle
- src/components/cart/CartSummary.tsx
- src/components/home/FlatlistHeaderComponent.tsx
- src/util/sumUp.ts
1. 메인화면 하단 사업자정보 추가
2. 배송날짜 공지
3. cartSummary 디자인 수정
4. cartSummary 판매자별 식품 검색기능 추가
> [RELEASE] version 1.0.3 (23.12.05)

- android/app/build.gradle
- src/components/cart/MenuNumSelectContent.tsx
1. 앱스토어심사 요구사항 수정 (목표영양 레퍼런스, 안드로이드 statusBar 제거)
2. 결제로딩 중 iamport 로고 말고 dietmate로고 보여주기 적용
3. redux initialize에는 Object.assign 사용
4. appleLogin 기능 추가
5. 끼니 수량조절 기능 개선 [Cart], [Home]
6. 자동구성에 원하는 판매자 식품을 포함하는 기능 추가
(23.12.11 added by 대갈딱딱이)
> [RELEASE]: version 1.0.4 (23.12.11)

- src/components/cart/CartSummary.tsx
- src/constants/constants.ts
- src/screens/myPageScreen/orderHistory/OrderHistory.tsx
- src/screens/myPageScreen/orderHistory/OrderHistoryDetail.tsx
- src/screens/orderScreen/Order.tsx
1. <Order.tsx> 에 BtnBottomCTA 에 배송비가 그냥 3000원 constant로 들어가 있었음
(23.12.13 fixed by 대갈딱딱이)
> [FIX]: [Order] 스크린 하단 주문CTA버튼에 배송비가 포함되지 않은 문제 수정

- src/components/cart/CartSummary.tsx
- src/components/cart/MenuNumSelectContent.tsx
- src/screens/myPageScreen/orderHistory/OrderHistory.tsx
- src/screens/orderScreen/SelfOrder.tsx
- src/util/common/regroup.ts
- src/util/sumUp.ts
1. 날짜, dietNo 별로 regroup 하는 함수 util로 빼서 정리
2. util의 sumUp 파일 중 regroup 기능은 regroup파일로 이동
(23.12.17 refactored by 대갈딱딱이)
> [REFACTOR] : refactor [OrderHistory]

- src/screens/Login.tsx
1. ios 확인은 constant에 있는 값 사용
(23.12.17 refactored by 대갈딱딱이)
> [REFACTOR] : refactor [Login]

- src/components/cart/CartSummary.tsx
- src/components/payment/KakaoPay.tsx
- src/screens/myPageScreen/orderHistory/OrderHistory.tsx
- src/screens/myPageScreen/orderHistory/OrderHistoryDetail.tsx
- src/screens/orderScreen/Order.tsx
- src/util/common/regroup.ts
- src/util/sumUp.ts
(불필요한 반복loop 제거)
1. OrderHistoryDetail.tsx refactoring
2. 총 배송비 구하는 함수 수정 -> getShippingPrice
(23.12.19 refactored by 대갈딱딱이)
> [REFACTOR] : refactor [OrderHistoryDetail]

- src/components/cart/CartSummary.tsx
- src/components/cart/MenuNumSelectContent.tsx
- src/screens/myPageScreen/orderHistory/OrderHistoryDetail.tsx
- src/screens/orderScreen/SelfOrder.tsx
- src/util/common/regroup.ts
- src/util/sumUp.ts
1. [OrderHistoryDetail]에서 배송비 합계 오류 수정 
(orderDetailData 의 shippingPrice는 주문에 대한 합계 배송비라 이미 합한 배송비가 중복으로 더해져서 오류 발생)
(23.12.20 fixed by 대갈딱딱이)
> [FIX] : fix shippingPriceError in [OrderHistoryDetail]

- android/app/build.gradle
1. [Order] 스크린 하단 주문CTA버튼에 배송비가 포함되지 않은 문제 수정
2. [REFACTOR] : refactor [OrderHistory]
3. [REFACTOR] : refactor [Login]
4. [REFACTOR] : refactor [OrderHistoryDetail]
5. [FIX] : fix shippingPriceError in [OrderHistoryDetail]
(23.12.20 added by 대갈딱딱이)
> [RELEASE] : version 1.0.5 (23.12.20)

- src/components/foodDetail/NutrientPart.tsx
- src/query/queries/member.ts
- src/query/types/member.ts
- src/screens/FoodDetail.tsx
- src/screens/myPageScreen/Account.tsx
- src/util/foodDetail/makeNutrTable.ts
1. stylesheet -> styledComponent로 전환
2. 당류, 트랜스지방, 포화지방 표 들여쓰기
3. useGetProfile -> 서버 api에 맞춰 useGetUser로 변경 (react-query에 IUser type도 적용)
(23.12.21 added by 대갈딱딱이)
> [REFACTOR] : refactor [FoodDetail] screen

- src/util/cart/autoMenu2.ts
- src/util/sumUp.ts
1. 메인 함수인 makeAutoMenu2 refactoring 
(errRange 내/외 메뉴 구분해서 메뉴 선택하는 기능 함수로 분리)
(23.12.23 added by 대갈딱딱이)
> [REFACTOR] : refactor <autoMenu2.ts>

- src/components/cart/MenuNumSelectContent.tsx
1. "전체 끼니 중" 텍스트는 의미가 모호함 -> "해당 식품사 총 금액" 으로 변경
(23.12.23 fixed by 대갈딱딱이)
> [FIX] : <MenuNumSelectContent.tsx> 텍스트 수정

- src/components/order/Address.tsx
- src/components/payment/KakaoPay.tsx
- src/components/payment/Loading.tsx
- src/constants/constants.ts
- src/screens/orderScreen/Order.tsx
- src/screens/orderScreen/types/paymentInfo.d.ts
- src/stores/slices/userInputSlice.ts
- src/util/order/backEventHook.tsx
- src/util/userInput/validation.ts
1. kakaopayData에 pg: kakaopay.${KAKAOPAY_CID} 추가
2. iamport usercode constant.ts에 만들기
3. kakaopayData customData에 식품들 정보 추가(iamport관리자에서 확인가능하도록)
4. 결제로딩시 앱아이콘 이미지 크기 축소
5. 받는분 정보 삭제
(23.12.27 added by 섭)
> [FEAT] : iamport 실결제 전환 및 수정 (식품정보 customData 추가)

- src/components/home/FoodList.tsx
1. 슬라이드로 식품 추가 삭제가 직관성 떨어짐. 제거.
(23.12.28 added by 섭)
> [FEAT] : <FoodList.tsx> delete slide animation

- src/components/order/Address.tsx
- src/screens/orderScreen/AddressEdit.tsx
- src/screens/orderScreen/Order.tsx
- src/stores/slices/userInputSlice.ts
- src/util/userInput/validation.ts
1. 주소찾기 외부 터치시 모달 닫기
2. 상세주소 없으면 주문 안되도록 가이드 텍스트 넣음
(23.12.28 added by 섭)
> [FEAT] : [AddressEdit] 주소찾기 외부 터치시 모달 닫기, 주문버튼 가이드 텍스트

- src/screens/Cart.tsx
1. safeareaview 는 자체 padding값 가짐. padding 적용 위해 view로 변환
(23.12.28 added by 섭)
> [FIX] : [Cart] safeareaview padding 적용 안되는 문제 해결

- src/components/common/textInput/DTextInput.tsx
- src/components/myPage/CalorieChangeAlert.tsx
- src/components/myPage/NutrientChangeAlert.tsx
- src/components/myPage/WeightChangeAlert.tsx
- src/components/order/Address.tsx
- src/components/order/Orderer.tsx
- src/components/userInput/CalculateByRatio.tsx
- src/components/userInput/Manual.tsx
- src/screens/orderScreen/AddressEdit.tsx
- src/screens/userInputScreen/FirstInput.tsx
- src/screens/userInputScreen/SecondInput.tsx
- src/styles/styledConsts.tsx
1.  기존 styledComponent textInput을 component로 따로 만들어서 props에 placeholderColor props 추가
(placeholderColor는 스타일로 적용 불가능하고 reactNative TextInput Component props로 설정 가능)
(23.12.30 added by 섭)
> [FIX] : fix invisible textInput placeholder color in ios device

- src/screens/myPageScreen/Notice.tsx
1. 공지사항에 한국인영양소섭취기준 한국영양학회 링크 첨부
2. 공지사항에 문의하기 버튼은 삭제
(23.12.30 added by 섭)
> [FEAT] : 공지사항에 한국인영양소섭취기준 참고문헌 자료 추가

- src/components/userInput/Auto.tsx
- src/screens/Guide.tsx
1. [Guide]페이지 pressable 대신 text자체의 onPress로 링크 동작
2. [ThirdInput] 페이지 <Auto.tsx> 에서도 링크 추가
(23.12.31 added by 섭)
> [FEAT] : 한국인 영양섭취기준 참고문헌 링크 추가

- android/app/build.gradle
1. [REFACTOR] : [FoodDetail] screen, <autoMenu2.ts>, <userInputSlice.ts>, <Order.tsx>, <AddressEdit.tsx>
2. [FEAT] : change AccordionInactiveHeader subTitle
3. [FEAT] : iamport 실결제 전환 및 수정 (식품정보 customData 추가)
4. [FEAT] : <FoodList.tsx> delete slide animation
5. [FEAT] : [AddressEdit] 주소찾기 외부 터치시 모달 닫기, 주문버튼 가이드 텍스트
6. [FIX] : [Cart] safeareaview padding 적용 안되는 문제 해결
7. [FIX] : fix invisible textInput placeholder color in ios device
8. [FIX] : 에러 알럿창에서 특정 에러의 경우 로그인으로 돌아가지 않는 문제 발생
9. [FEAT] : 공지사항에 한국인영양소섭취기준 참고문헌 자료 추가
(23.12.31 added by 섭)
> [RELEASE] : version 1.0.6 (23.12.31)

- src/screens/Login.tsx
1. 나중 카드심사 등 guestLogin 버튼이 필요할 때 다시 추가할 예정 (주석처리)
(24.01.03 added by 섭)
> [FEAT] : guestLogin 버튼 삭제

- src/components/common/textInput/DTextInput.tsx
- src/components/myPage/CalorieChangeAlert.tsx
- src/components/myPage/NutrientChangeAlert.tsx
- src/components/myPage/WeightChangeAlert.tsx
- src/components/order/Address.tsx
- src/components/order/Orderer.tsx
- src/components/userInput/CalculateByRatio.tsx
- src/components/userInput/Manual.tsx
- src/constants/constants.ts
- src/screens/orderScreen/AddressEdit.tsx
- src/screens/userInputScreen/FirstInput.tsx
- src/screens/userInputScreen/SecondInput.tsx
- src/stores/slices/userInputSlice.ts
- src/styles/styledConsts.tsx
1. 기본 색상 실기기에서 안보이는 것 수정
2. validation 에 따라 텍스트 색상 변경되도록 수정
3. onFocus에 ref scroll 있는 경우 50 -> 150으로 수정해서 동작 안되는 것 수정
4. calorie(cal, protein, fat)Change 할 때도 validation 적용
> [FIX] : textInput 텍스트색상 오류 수정

- android/app/build.gradle
1. guestLogin 버튼 삭제
2. [ThirdInput] CTA버튼 비활성화 (validation)오류 수정
3. [Home] searchText 초기화시 flatlist초기화
4. textInput 텍스트 색상오류 수정
(24.02.13 added by 섭)
> [RELEASE] : version 1.0.7 (24.02.13)

- src/components/foodDetail/ShippingPart.tsx
- src/screens/FoodDetail.tsx
> [FEAT] : 배송정책 공식쇼핑몰 링크 추가

- src/components/cart/AccordionContent.tsx
- src/components/cart/AccordionInactiveHeader.tsx
- src/components/cart/MenuNumSelect.tsx
- src/components/cart/MenuNumSelectContent.tsx
- src/components/common/menuSection/MenuSection.tsx
1. 버튼 자체 disabled prop 대신 onPress 자체에서 동작 없도록 함
(24.02.16 added by 섭)
> [FEAT] : MenuNumSelect 버튼 disabled인 경우 눌렸을 때 홈화면 장바구니 닫힘 수정

- src/query/keys.ts
- src/query/queries/guest.ts
- src/query/queries/urls.ts
- src/query/types/guest.ts
- src/screens/Login.tsx
1. 서버주소변경 (54.180.96.237)
2. 앱심사용 게스트로그인 사용유무를 서버 값으로 결정
(24.02.19 added by 섭)
> [FEAT] : 서버주소 변경, 로그인시 guest login 사용유무 서버값 조회

- src/query/queries/urls.ts
1. 서버주소 재변경 (43.201.101.22)
2. guest login 사용유무 api (member전용 -> every) 수정
(24.02.20 added by 섭)
> [FIX] : 서버주소 변경, 로그인시 guest login 사용유무 서버값 조회 (5dd666 수정)

- src/components/common/error/ErrorAlert.tsx
- src/components/common/menuSection/MenuSection.tsx
- src/components/common/nutrient/NutrientsProgress.tsx
- src/components/home/FoodList.tsx
- src/query/queries/address.ts
- src/query/queries/baseLine.ts
- src/query/queries/category.ts
- src/query/queries/diet.ts
- src/query/queries/guest.ts
- src/query/queries/member.ts
- src/query/queries/order.ts
- src/query/queries/product.ts
- src/query/types/common.ts
- src/screens/Home.tsx
- src/screens/myPageScreen/Account.tsx
- src/screens/userInputScreen/ThirdInput.tsx
1. [MenuSection]에서 baselineData 사용할 때 빈 오브젝트 꼭 확인해야함 (Object.keys(baselineData).length === 0)
2. useQuery onError, onSuccess 삭제 (에러처리는 아직 안되어있음)
(24.02.23 added by 섭)
> [FIX] : 계정삭제 후 홈화면 이동시 ProgressBar 오류 | useQuery onError, onSuccess삭제

- src/components/common/menuSection/MenuSection.tsx
dietNo 바뀔 때 accordion activeSection 초기화
(24.02.24 added by 섭)
> [FIX] : dietNo 바뀔 때 (diet생성 or 전환) [MenuSection] 깨짐 수정

- android/app/build.gradle
1. progressBar accordion 적용
2. progressBar tooltip 잘리는 오류 수정
3. 배송정책 및 공식쇼핑몰 링크추가
4. MenuNumSelect 버튼 동작오류 수정
5. 서버주소변경
6. axios request timeout 추가
7. 게스트로그인 사용유무 api 추가
8. [FoodDetail] 이전 페이지의 상품정보 보이는 문제 수정
9. useQuery onError, onSuccess 제거 (react-query 버전업을 위함)
10. dietNo 바뀔 때 MenuSection 깨짐 수정
(24.02.24 added by 섭)
> [RELEASE] : version 1.0.8 (24.02.24)

- android/app/build.gradle
1. react-native version 0.72.6 -> 0.73.5
2. ios minor update -> [Input] CTA버튼 잘림현상 해결, refactor react-query error handling,  로그인화면 폰트 Kotra Hope 적용
(24.02.27 added by 섭)
> [RELEASE] : version 1.0.9

- src/components/foodDetail/FoodPart.tsx
- src/screens/Login.tsx
- yarn.lock
1. 미리 이미지의 크기를 불러와서 모바일 화면 크기로 맞추는 작업을 state에 저장할 때 렌더링 1번으로 최소화
2. 이미지 로딩이 실패했을 때 대체 이미지를 띄워주는 작업
3. appleLogin.tsx -> AppleLogin.tsx (git pull 오류) 수정
(24.03.01 added by 섭)
> [FIX] : [FoodDetail] image loading 오류 처리.

- src/components/common/nutrient/NutrientsProgress.tsx
- src/query/queries/diet.ts
- src/screens/Likes.tsx
- src/styles/colors.ts
1. markProduct에 대해서는 optimistic update적용 안되어있었음
(24.03.01 added by 섭)
> [FIX] : [Likes] foodlist에서 식품 추가/삭제할 때 오류 수정 (500error)

- src/components/cart/MenuNumSelectContent.tsx
- src/components/foodDetail/FoodPart.tsx
- src/screens/Cart.tsx
- src/screens/Login.tsx
- src/screens/userInputScreen/ThirdInput.tsx
1. 첫 로그인 시 끼니 2개 생성되는 오류 수정
2. 수량조절모달에서 다른 끼니에 있는 가격은 합산되지 않은 것 수정
3. 식품명, 가격이 width 벗어나는 스타일오류 수정
4. ios로그인도 guestYn에 따라 노출
5. 식품상세정보 이미지 promise 적용
(24.03.04 added by 섭)
> [FIX] : 첫 로그인 시 끼니 2개 생성오류 수정. 수량조절모달 오류 수정. 식품상세이미지 오류수정.

- android/app/build.gradle
1. 계정삭제시 오류, lottie 오류, 식품추가삭제, 상세정보 이동 버튼범위 수정
2. 앱스토어 심사거절 항목 수정
3. [FoodDetail] 이미지 로딩 오류 처리
4. 첫 로그인 시 끼니 2개 생성되는 오류 수정
5. 수량조절모달 오류 수정
(24.03.04 added by 섭)
> [RELEASE] : version 1.0.10 (24.03.04)

- ios/Podfile.lock
- src/screens/Login.tsx
> [FIX]: GuestLogin 2개 수정

- src/screens/myPageScreen/Account.tsx
- src/screens/userInputScreen/ThirdInput.tsx
Account.tsx에서 Login화면 보내주는 코드제거, ThridInput 완료 버튼 가려져서 ScrollView로 한번 감싸줌
> [FIX]: 1. IOS계정 삭제 수정 2. ThridInput UI 수정

- android/app/build.gradle
1. 게스트로그인 2개 오류 수정
2. IOS계정삭제 오류 수정
(24.03.06 added by 섭)
> [RELEASE] : version 1.0.11

- src/components/cart/MenuNumSelectContent.tsx
1. 빈끼니에서 dietNo 값이 없어서 오류. optional chaining으로 해결
(24.03.06 added by 섭)
> [FIX] : <MenuNumSelectContent.tsx>에서 빈끼니 있을 때 수량조절하면 오류나는 이슈 해결

- android/app/build.gradle
1. 빈끼니 있을 때 수량조절오류
(24.03.06 added by 섭)
> [RELEASE] : version 1.0.12

- android/app/build.gradle
- package.json
1. order custom data 의 addr1, addr2 구분 추가
2. RN-bootsplash 추가
(24.03.14 added by 섭)
> [RELEASE] : version 1.0.13

- App.tsx
- ios/DietMate.xcodeproj/project.pbxproj
- ios/Podfile.lock
- src/components/home/FilterModalContent.tsx
- src/screens/userInputScreen/SecondInput.tsx
- src/screens/userInputScreen/ThirdInput.tsx
- src/styles/styledConsts.tsx
1. 필터모달에서 취소, 완료 버튼 UI 수정 2. ThirdInput UI 수정
> [FIX]: 1. 필터모달에서 취소, 완료 버튼 UI 수정 2. ThirdInput UI 수정

- App.tsx
- cmd
- package.json
- src/query/queries/urls.ts
- src/query/queries/version.ts
- yarn.lock
1. package.json에서 current app version 저장
2. 서버에 latest app version 저장해서
3. 비교 후 버전 정보 안맞으면 업데이트 페이지로 이동
(24.03.22 added by 섭)
> [FEAT] : latest version check

- android/app/build.gradle
- package.json
1. 필터 모달 취소, 완료버튼 | ThirdInput 완료버튼 ios 하단 겹침 수정.
2. 최신 업데이트 버전 확인 및 업데이트 알림 추가.
(24.03.22 added by 섭)
> [RELEASE] : version 1.0.14

- ios/DietMate.xcodeproj/project.pbxproj
- ios/GoogleService-Info.plist
- ios/Podfile.lock
1. google service info
(24.04.02 added by 섭)
> [BUILD]: ios build 필요파일 추가

- ios/AppCenter-Config.plist
- ios/DietMate.xcodeproj/project.pbxproj
- ios/DietMate/AppDelegate.mm
- ios/DietMate/Info.plist
- ios/Podfile.lock
> [FEAT]: ios CodePush 설정 완료

- android/app/build.gradle
- ios/DietMate.xcodeproj/project.pbxproj
- ios/DietMate/Info.plist
- ios/Podfile.lock
- ios/PrivacyInfo.xcprivacy
- package.json
1. cartSummary price, menuNumSelect modal price 안맞는 문제 해결
2. android, ios codepush 설정
(24.04.12 added by 섭)
> [RELEASE]: version 1.0.17 (24.04.12)

- App.tsx
- src/components/cart/AutoDietModal.tsx
- src/components/menuAccordion/AccordionCtaBtns.tsx
- src/screens/autoMenu/subScreens/Processing.tsx
- src/screens/diet/Diet.tsx
- src/screens/diet/ui/AddMenuBtn.tsx
- src/screens/diet/util/cartCustomHooks.ts
- src/screens/diet/util/modalContent.tsx
- src/shared/utils/autoMenu2.ts
- src/shared/utils/customHooks.tsx
1. ios는 Modal 여러개 사용 못함. 모달 하나로 합치고 렌더링할 content만 분리
2. automenu useAsync로 실행하는 것 문제 있음. (<AccordionCtaBtns.tsx>에서 바로 자동구성 상태(redux)를 조절하고 서버 mutation까지 진행
(24.05.02 added by 섭)
> [FEAT]: tutorial 기능 ios 오류수정 (multiple modal -> single modal)

- android/app/build.gradle
build.gradle 파일 defaultConfig 수정
-> resValue 'string', "CODE_PUSH_APK_BUILD_TIME", String.format("\"%d\"", System.currentTimeMillis())
(24.05.09 added by 섭)
> [FIX]: 코드푸시 적용 안되는문제 확인 중

- android/app/build.gradle
- ios/DietMate.xcodeproj/project.pbxproj
- package.json
- src/screens/home/NewHome.tsx
1. shadow 라이브러리 제거 styledComponent로 동시적용-> 끊김해결
2. 코드푸시 적용 안되는 문제는 아직 미해결
(24.05.19 added by 섭)
> [RELEASE]: version 1.0.19 (24.05.10)

- ios/DietMate.xcodeproj/xcshareddata/xcschemes/DietMate.xcscheme
- ios/DietMate/Info.plist
1. info.plist versioning
(24.05.11 added by 섭)
> [RELEASE]: version 1.0.19 !!Ios+Android!!

- android/settings.gradle
- app.json
- index.js
- ios/DietMate.xcodeproj/project.pbxproj
- ios/DietMate.xcodeproj/xcshareddata/xcschemes/DietMate.xcscheme
- ios/DietMate.xcworkspace/contents.xcworkspacedata
- ios/DietMate/AppDelegate.mm
- ios/DietMate/Info.plist
- ios/DietMateTests/DietMateTests.m
- ios/Podfile
- ios/Podfile.lock
- package.json
1. ios, android 앱이름 관리가 따로 되는 것 방지
(24.05.28 added by 섭)
> [CHORE]: change appName DietMate to dietmate

- src/screens/home/NewHome.tsx
1. dTOData 가져와서 menuNum (memo) 설정되기 전에 useEffect가 터짐 => deps에 dTOData, menuNum 추가하고 !dTOData 이거거나 menuNum 0일때는 return
> [FIX]: Fixing the tutorial diet delete all

- ios/DietMate/AppDelegate.mm
- ios/Podfile.lock
RN 0.74이상 버전인 경우 BootSplash setting 바뀜
> [FIX]: ios bootsplash settings

- src/screens/home/NewHome.tsx
7ee451 msg
dTOData 가져와서 menuNum (memo) 설정되기 전에 useEffect가 터짐
=> deps에 dTOData, menuNum 추가하고 !dTOData 이거거나 menuNum 0일때는 return
위처럼 적용했을 때 menuNum 이 0 이면
tutorial CtaBtn 위치 조정이 스킵되는 문제 해결
> [FIX]: Fixing the new home tutorial (7ee451 개선)

- src/screens/order/Order.tsx
- src/shared/utils/sumUp.ts
1. regroupedBySeller[p.platformNm] = [{...p}] dTOData가 shallow copy 되어서 발생한 문제
> [FIX]: 끼니 수량 비정상적으로 올라가는 문제 해결

- react-native-config.d.ts
- src/app/navigators/RootStackNav.tsx
- src/components/payment/Loading.tsx
- src/components/payment/Payment.tsx
- src/features/reduxSlices/orderSlice.ts
- src/screens/order/Order.tsx
- src/screens/order/ui/Address.tsx
- src/screens/order/ui/PaymentMethod.tsx
- src/screens/order/util/setPayData.ts
- src/shared/api/queries/order.ts
- src/shared/api/queries/payment.ts
- src/shared/ui/styledComps.tsx
- src/shared/utils/dataTransform.ts
- src/shared/utils/handleError.ts
1. pay parameter refactoring
2. 스마트로 일반결제 추가
3. 결제성공여부 확인로직 추가 (iamport api 사용)
> [FEAT]: 일반결제수단 추가 (!!!실결제 테스트 필요!!!)

- App.tsx
- src/components/appLoading/AppLoading.tsx
- src/components/common/error/ErrorAlert.tsx
- src/screens/login/Login.tsx
- src/screens/login/ui/AppleLogin.tsx
- src/shared/api/queries/baseLine.ts
- src/shared/api/queries/login.ts
- src/shared/utils/navigateByUserInfo.tsx
기존 App.tsx에서 splash screen 띄우고 로딩하던 것 AppLoading 컴포넌트로 분리
> [REFACTOR]: splash loading component 추가

- src/components/menuAccordion/MenuAcActiveHeader.tsx
- src/components/menuAccordion/MenuAcInactiveHeader.tsx
[Diet] accordion 열려있을 때 끼니 삭제시 오류 해결
(dDData.dietSeq가 아니라 dTOData?.[dietNo]?.dietSeq로 접근해야함)
> [FIX]: 끼니삭제 오류 해결

- android/app/build.gradle
- ios/DietMate/Info.plist
- package.json
1. 식품변경시 현재 식품과 같은 식품 나오는 문제 해결
2. 업데이트 필요 알럿창에 현재버전, 최신버전 표시 (안드로이드 디바이스에서 버전 오류 디버깅 목적)
> [RELEASE]: version 1.0.22

- android/app/build.gradle
1. 네이버 페이 추가
2. Diet 페이지 오류 수정
> [RELEASE]: version 1.0.22 (hotfix)

- src/components/common/menuSection/MenuSection.tsx
- src/components/common/menuSection/MenuSelectCard.tsx
- src/screens/userInput/util/contentBypages.tsx
1. 중복으로 끼니 추가 안되도록 activityIndicator 및 버튼 disabled 설정
2. userInput result text 변경
> [FIX]: 중복으로 끼니 추가 안되도록 함

- src/screens/diet/Diet.tsx
- src/screens/home/NewHome.tsx
- src/shared/utils/handleError.ts
1. queryClient.invalidateQueries() => queryClient.clear()
> [FIX]: 401에러 발생시 invalidation으로 인한 무한루프 수정

- src/screens/userInput/UserInput.tsx
> [FIX]: [UserInput] CTA button is hidden by textInput (-> keyboardAvoidingView 적용)
